version: '3.8'

services:
  db:
    ports:
      - 5432:5432
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${{ secrets.DATASOURCE_USERNAME }}
      - POSTGRES_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
    restart: always

  app:
    ports:
      - 8080:8080
    image: '1998bal/bookstore:v1'
    build:
      context: .
    container_name: bookstore
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=${{ secrets.DATASOURCE_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always