name: Java CI with Testcontainers

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (e.g., Java 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Step 3: Set up Docker (required for Testcontainers)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 4: Cache Maven dependencies (optional, for faster builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Run tests
      - name: Run Maven tests
        run: mvn clean test