name: Build and Test All Maven Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-projects:
    runs-on: ubuntu-latest

    # Matrix strategy to handle multiple projects
    strategy:
      matrix:
        project:
          - bookstore-main
          - in-memory-db-starter
          - spring-data-jpa

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK (adjust version if needed)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Adjust the version based on your project's requirements
          distribution: 'temurin'

      # Step 3: Navigate to the correct project directory and run Maven commands
      - name: Build and Test
        working-directory: ${{ matrix.project }} # Change directory dynamically based on the project
        run: mvn clean install
