name: Build All Maven Projects

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 5432:5432

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build all projects using the parent POM
      - name: Build All Modules
        run: mvn clean install

      # Set up Docker (Check Docker version and status)
      - name: Set up Docker
        run: docker --version

      # Ensure Docker service is running
      - name: Check Docker status
        run: sudo systemctl status docker
